version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8@sha256:0b549bf7e1539451cd501e94a2d49bbb0b91370fec2b7817d3a131f412fadd89
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:latest@sha256:4bee009f05db292e794d4c288b587be60c3a526cc3bf669100be981ef0551284
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
